enum SignTypes {
  SIGN_MESSAGE = 'SIGN_MESSAGE',
  SIGN_MESSAGE_SUCCESS = "SIGN_MESSAGE_SUCCESS",
  SIGN_MESSAGE_FAILURE = "SIGN_MESSAGE_FAILURE",
  VERIFY_MESSAGE = 'VERIFY_MESSAGE',
  VERIFY_MESSAGE_SUCCESS = "VERIFY_MESSAGE_SUCCESS",
  VERIFY_MESSAGE_FAILURE = "VERIFY_MESSAGE_FAILURE",
}

export default SignTypes;
