enum LoopTypes {
  SET_LOOP_URL = 'SET_LOOP_URL',
  SET_LOOP_URL_SUCCESS = 'SET_LOOP_URL_SUCCESS',
  SET_LOOP_URL_FAILURE = 'SET_LOOP_URL_FAILURE',

  GET_LOOP_OUT_TERMS = 'GET_LOOP_OUT_TERMS',
  GET_LOOP_OUT_TERMS_SUCCESS = 'GET_LOOP_OUT_TERMS_SUCCESS',
  GET_LOOP_OUT_TERMS_FAILURE = 'GET_LOOP_OUT_TERMS_FAILURE',

  GET_LOOP_IN_TERMS = 'GET_LOOP_IN_TERMS',
  GET_LOOP_IN_TERMS_SUCCESS = 'GET_LOOP_IN_TERMS_SUCCESS',
  GET_LOOP_IN_TERMS_FAILURE = 'GET_LOOP_IN_TERMS_FAILURE',

  GET_LOOP_OUT_QUOTE = 'GET_LOOP_OUT_QUOTE',
  GET_LOOP_OUT_QUOTE_SUCCESS = 'GET_LOOP_OUT_QUOTE_SUCCESS',
  GET_LOOP_OUT_QUOTE_FAILURE = 'GET_LOOP_OUT_QUOTE_FAILURE',

  GET_LOOP_IN_QUOTE = 'GET_LOOP_IN_QUOTE',
  GET_LOOP_IN_QUOTE_SUCCESS = 'GET_LOOP_IN_QUOTE_SUCCESS',
  GET_LOOP_IN_QUOTE_FAILURE = 'GET_LOOP_IN_QUOTE_FAILURE',

  LOOP_OUT = 'LOOP_OUT',
  LOOP_OUT_SUCCESS = 'LOOP_OUT_SUCCESS',
  LOOP_OUT_FAILURE = 'LOOP_OUT_FAILURE',

  LOOP_IN = 'LOOP_IN',
  LOOP_IN_SUCCESS = 'LOOP_IN_SUCCESS',
  LOOP_IN_FAILURE = 'LOOP_IN_FAILURE',

  LIST_SWAPS = 'SWAPS',
  LIST_SWAPS_SUCCESS = 'LIST_SWAPS_SUCCESS',
  LIST_SWAPS_FAILURE = 'LIST_SWAPS_FAILURE',

  RESET_LOOP = 'RESET_LOOP',

  SYNC_LOOP_STATE = 'SYNC_LOOP_STATE',

  // CHARM types
  ACTIVATE_CHARM = 'ACTIVATE_CHARM',
  ACTIVATE_CHARM_SUCCESS = 'ACTIVATE_CHARM_SUCCESS',
  ACTIVATE_CHARM_FAILURE = 'ACTIVATE_CHARM_FAILURE',

  DEACTIVATE_CHARM = 'DEACTIVATE_CHARM',
  DEACTIVATE_CHARM_SUCCESS = 'DEACTIVATE_CHARM_SUCCESS',
  DEACTIVATE_CHARM_FAILURE = 'DEACTIVATE_CHARM_FAILURE',
}

export interface CharmPayload {
  id: string;
  isCharmEligible: boolean;
  isCharmEnabled: boolean;
}

export default LoopTypes;
