enum SettingsTypes {
  CHANGE_SETTINGS = 'CHANGE_SETTINGS',
  LOAD_SETTINGS = 'LOAD_SETTINGS',
  CLEAR_SETTINGS = 'CLEAR_SETTINGS',

  ADD_ENABLED_DOMAIN = 'ADD_ENABLED_DOMAIN',
  REMOVE_ENABLED_DOMAIN = 'REMOVE_ENABLED_DOMAIN',
  
  ADD_REJECTED_DOMAIN = 'ADD_REJECTED_DOMAIN',
  REMOVE_REJECTED_DOMAIN = 'REMOVE_REJECTED_DOMAIN',
}

export default SettingsTypes;
